Provide the option to pass the title for an iframe
kylemocode/react-lite-yt-embed pull request #12
Opened 2021-06-03 20:26 UTC by mvshmakov

Hey, thanks for the package!

Currently, it is considered a best practice to pass the title for an iframe. The Lighthouse considers this as an issue: https://web.dev/frame-title/. PR provides support for it.

2021-06-03 20:32 UTC, mvshmakov commented
Could you please also make a new version in an NPM when this gets merged?

2021-06-04 13:21 UTC, kylemocode commented
> Could you please also make a new version in an NPM when this gets merged?

I will handle this next week because I am in army now...
Thanks for your PR !

2021-06-10 02:39 UTC, kylemocode requested changes

2021-06-22 16:28 UTC, mvshmakov commented on dist/index.js
> -module.exports = require('./react-lite-yt-embed.esm.js')
Done, thanks!

2021-06-23 12:46 UTC, kylemocode approved these changes

2021-06-23 12:46 UTC, merged

2021-06-23 12:54 UTC, kylemocode commented
> Hey, thanks for the package!
> 
> Currently, it is considered a best practice to pass the title for an iframe. The Lighthouse considers this as an issue: https://web.dev/frame-title/. PR provides support for it.

@mvshmakov Now the latest version is @1.2.7